config/routes.rb
Rails.application.routes.draw do
  # root 'shows#index'
  root 'sessions#index'
  resources :shows
  post '/shows/search_tmdb'
  get '/shows/search_id/:id', to: 'shows#search_id'
  get '/shows/get_ep/:id/:season/:ep', to: 'shows#get_ep'
  get '/shows/get_ep_info/:id/:season/:ep', to: 'shows#get_ep_info'
  get '/about', to: 'shows#about'
  
  
  get  'auth/:provider/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get  'auth/failure' => 'sessions#failure'
  get  'auth/facebook', :as => 'login'
  
end

app/models/show.rb
class Show < ActiveRecord::Base
    belongs_to :user
    
    def addExtraInformation
        show = Tmdb::TV.detail(self.show_id)
        if category == 'Bookmark'
            offset = 1
            if show.seasons[0].season_number == 0
                offset = 0
            end
            if show.seasons[self.season - offset].poster_path.blank?
                self.image = show.poster_path
            else
                self.image = show.seasons[self.season - offset].poster_path
            end
        elsif category == 'Watchlist' or category == 'Archive'
            self.image = show.poster_path
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :shows, dependent: :destroy
    
    def self.create_with_omniauth(auth)
        User.create!(
            :provider => auth["provider"],
            :uid => auth["uid"],
            :name => auth["info"]["name"])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :set_current_user
  
  protected # prevents method from being invoked by a route
  def set_current_user
      @current_user ||= User.find_by(id: session[:user_id])
      redirect_to root_path and return unless @current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # user shouldn't have to be logged in before logging in!
    skip_before_filter :set_current_user
    
    def index
        loggedIn = User.find_by(id: session[:user_id])
        if !loggedIn.blank?
            redirect_to shows_path and return
        end
    end
    
    def create
        auth = request.env["omniauth.auth"]
        user = User.find_by(provider: auth["provider"], uid: auth["uid"]) || User.create_with_omniauth(auth)
        session[:user_id] = user.id
        redirect_to shows_path
    end
    
    def destroy
        session.delete(:user_id)
        flash[:notice] = 'Logged out successfully.'
        redirect_to shows_path
    end
    
    def failure
        flash[:warning] = "Sorry, couldn't authenticate with Facebook"
        redirect_to root_path
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  def index
    shows = Show.where(user_id: @current_user.id)
    @bookmarks = shows.where(category: "Bookmark")
    @watchlist = shows.where(category: "Watchlist").order(priority: :desc)
    @archive = shows.where(category: "Archive")
    
    @config = Tmdb::Configuration.get
    @base_url = @config.images.secure_base_url
    @poster_size = @config.images.poster_sizes[2]
    @xs_poster_size = @config.images.poster_sizes[1]
  end
  
  def about
  end

  def show
  end

  def new
    @show = Show.new
  end
  
  def search_tmdb
    @name = params[:search_terms]
    @search = 0
    if !@name.blank?
      @search = Tmdb::Search.tv(@name)
    end
    @config = Tmdb::Configuration.get
    @base_url = @config.images.secure_base_url
    @poster_size = @config.images.poster_sizes[0]
  end
  
  def search_id
    @id = params[:id]
    @show = Tmdb::TV.detail(@id)
    @seasons = @show.number_of_seasons
    @offset = 0
    # skip season 0 (special episodes) if it exists
    if !@show.seasons[0].blank? and @show.seasons[0].season_number == 0
      @offset = 1
    end
    @show.seasons.reverse_each do |season|
      if season.season_number != 0 and !Date.parse(season.air_date).past?
        @seasons -= 1
      end
    end
  end

  def get_ep
    @id = params[:id]
    @season = params[:season]
    @episodes = params[:ep]
  end
  
  def get_ep_info
    @id = params[:id]
    @season = params[:season]
    @ep = params[:ep]
    @episode = Tmdb::Tv::Episode.detail(@id, @season, @ep)
    @stills = Tmdb::Tv::Episode.posters(@id, @season, @ep)
    @details = Tmdb::TV.detail(@id)
    @name = @details.name
    
    @config = Tmdb::Configuration.get
    @base_url = @config.images.secure_base_url
    @still_size = @config.images.still_sizes[2]
    
    @show = Show.new(name: @name, season: @season, episode: @ep)
  end

  def edit
  end

  def create
    @show = @current_user.shows.new(show_params)
    @show.addExtraInformation
    # @show = Show.new(show_params)
    if @show.save
      flash[:notice] = 'Show successfully created'
      redirect_to shows_path and return
    else
      flash[:warning] = 'Failed to add show'
      render 'new' 
    end
  end

  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.where(id: params[:id]).first
      
      # redirect if show doesnt exist
      if @show.blank?
        flash[:warning] = "Show doesn't exist"
        redirect_to shows_path and return
      end
      
      # check authorisation to look at this show
      if @show.user_id != @current_user.id
        flash[:warning] = 'Not authorised to view this page'
        @show = nil
        redirect_to shows_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      if params[:show].blank?
        raw_parameters = {
          show: {
            name: params[:name],
            season: params[:season],
            episode: params[:episode],
            show_id: params[:show_id],
            category: params[:category],
            priority: params[:priority]
          }
        }
        params = ActionController::Parameters.new(raw_parameters)
      end
      params.require(:show).permit(:name, :season, :episode, :show_id, :category, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %title ShowMark
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .wrapper
      - if flash[:notice]
        .notice.message= flash[:notice]
      - elsif flash[:warning]
        .warning.message= flash[:warning]

      - if !@current_user.blank?
        .nav.navbar.navbar-inverse
          .container-fluid
            .navbar-header
              %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", type: "button"}
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              = link_to"SHOWMARK", shows_path, class: "navbar-brand"
            .collapse.navbar-collapse#myNavbar
              %ul.nav.navbar-nav
                - if params[:action] == "about"
                  %li= link_to 'HOME', shows_path
                  %li.active= link_to 'ABOUT', about_path
                - else
                  %li.active= link_to 'HOME', shows_path
                  %li= link_to 'ABOUT', about_path
              %ul.nav.navbar-nav.navbar-right
                %li.dropdown
                  // = link_to shows_path, class: "dropdown-toggle" do
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"} 
                    #{@current_user.name}
                    %span.caret
                  %ul.dropdown-menu
                    %li
                      = link_to logout_path, :method => :post do
                        %span.glyphicon.glyphicon-log-out
                        Log Out
      
      = yield
    
    %footer.footer.nav.navbar-inverse
      .container-fluid
        .text-muted.text-center.footer-details
          Pouria Sterling 2017
          \|
          = link_to 'Contact', 'https://www.facebook.com/pouria.zebrahimi'
          \|
          = link_to 'https://github.com/PouriaSterling/ShowMark' do
            Contribute on GitHub
            = fa_icon "github"

app/views/shows/_episodeInfo.html.haml
%ul.list-group
    %li.list-group-item.list-group-item-info
        %strong #{@episode.name}
        -if !Date.parse(@episode.air_date).past?
            %i.warning (airs #{Date.parse(@episode.air_date).strftime("%d-%m-%Y")})
        -else
            %i (aired #{Date.parse(@episode.air_date).strftime("%d-%m-%Y")})
    %li.list-group-item.list-group-item-info #{@episode.overview}
    %li.list-group-item.list-group-item-info
        .row
            - @stills.each_with_index do |still, i|
                .btn
                    - break if i == 3
                    - if !still.file_path.blank?
                        = image_tag @base_url + @still_size + still.file_path, class: "img-fluid center"

%br
%h4{style: "margin-left: -20px;"}
    #{@name} -
    #{"S%02dE%02d" % [@season, @ep]}
    
-if Date.parse(@episode.air_date).past?
    = button_to "Save", '/shows', params: {name: @name, season: @season, episode: @ep, show_id: @id, category: 'Bookmark'}, class: "btn btn-success"
-else
    %i.warning Can't bookmark an unreleased episode
    = button_to "Save", '/shows', params: {name: @name, season: @season, episode: @ep, show_id: @id, category: 'Bookmark'}, class: "btn btn-success disabled"

app/views/shows/_form.html.haml
= form_for @show do |f|
  - if @show.errors.any?
    #warning
      #{pluralize(@show.errors.count, "error")} prohibited this show from being saved:
      %ul
        - @show.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :season
    = f.number_field :season
  .field
    = f.label :episode
    = f.number_field :episode
  .actions
    = f.submit 'Save'

app/views/shows/_selectSeason.html.haml
.row
    - (1..@seasons).step(1) do |i|
        = link_to "get_ep/#{@show.id}/#{i}/#{@show.seasons[i-1+@offset].episode_count}", controller: "shows", class: "btn btn-info", id: "season-#{i}", remote: true do
            Season #{i}

app/views/shows/_selectShow.html.haml
%h4 Select show
.row
    - @search.results.each_with_index do |show, i|
        - break if i == 3
        = link_to "nowhere", controller: "shows", class: "btn select-show", onclick: "showSelected(this)", 'data-id': "#{show.id}", 'data-name': "#{show.name}" , remote: true do
            .col-lg-2.col-md-3.col-sm-4.col-xs-6.choice-tiles{id: "show-#{i}-#{show.id}"}
                .center
                    %h5 
                        %strong #{show.name}
                .center
                    - if !show.poster_path.blank?
                        = image_tag @base_url + @poster_size + show.poster_path, class: "img-fluid center"

app/views/shows/_showTiles.html.haml
.container-fluid
    .row
        - shows.each do |show|
            .btn.text-center
                = link_to (image_tag @base_url + @poster_size + show.image, class: "visible-md visible-sm visible-lg", style: "width:100%;"), show, id: "#{show.name} button"
                = link_to (image_tag @base_url + @xs_poster_size + show.image, class: "visible-xs", style: "width:100%;"), show, id: "#{show.name} button -xs"

app/views/shows/_tmdbForm.html.haml
= form_tag('search_tmdb', id: "tmdb-form", remote: true) do
  %label{for: 'search_terms'} Show Name
  = text_field_tag 'search_terms'
  = submit_tag 'Search', id: "search"

app/views/shows/about.html.haml
.container-fluid.text-center
    .row
        .col-md-4.text-justify
            %h2 WHAT IS SHOWMARK
            %p
                SHOWMARK was born through a love for TV shows. It is a simple yet powerful 
                web app that, at its core, serves a dual purpose: to bookmark and archive your shows.
        
            %h4 
                &emsp;
                = fa_icon "bookmark"
                Bookmarking
            %p
                How many times have you tried to watch a show only to realise you have no
                idea where you're up to? I know I have and that's why SHOWMARK now exists!
                Since streaming websites like Netflix already offer this functionality, 
                SHOWMARK predominantly aims to cater for those poor forgotten shows not 
                available on these sites.
                    
                
            %h4 
                &emsp; 
                = fa_icon "archive"
                Archiving
            %p
                If you're anything like me, then you probably enjoy looking at stats like
                'How many total hours of shows have I watched', 'How many episodes of 
                breaking bad are there' or 'How far through Suits am I'. By adding your 
                shows to this site, you will get the answers to those questions and more in
                beautifully presented ways.
            %br  
            %p
                With new functionality added regularly and much more planned for the 
                future, SHOWMARK is continously transforming into a more informative and 
                useful website. Everything is open source, so if you would like to contribute 
                or learn more, visit the
                = link_to 'https://github.com/PouriaSterling/ShowMark' do
                    GitHub
                    = fa_icon "github"
    .row
        .col-md-4.text-justify
            %h2 BEHIND THE SCENES
            %p SHOWMARK is a Ruby on Rails application that uses the TMDb API but is not endorsed or certified by TMDb.
            = link_to (image_tag "https://www.themoviedb.org/assets/static_cache/27b65cb40d26f78354a4ac5abf87b2be/images/v4/logos/powered-by-rectangle-green.svg", class: 'tmdb-logo'), "https://www.themoviedb.org/"

app/views/shows/edit.html.haml
%h1 Editing show

= render 'form'

= link_to 'Show', @show
\|
= link_to 'Back', shows_path

app/views/shows/get_ep.js.haml
$('#episode-info-heading').hide();
$('#episode-info').hide();

$('#selection-episodes-heading').text('Which Episode?');
$('#selection-episodes-heading').show();

$('#selection-episodes').hide();
$('#selection-episodes').html('#{escape_javascript(render :partial => "selectEpisode")}');
$('#selection-episodes').slideDown(350);

app/views/shows/get_ep_info.js.haml
$('#episode-info-heading').text('Episode Information');
$('#episode-info-heading').show();

$('#episode-info').hide();
$('#episode-info').html('#{escape_javascript(render :partial => "episodeInfo")}');
$('#episode-info').slideDown(350);

app/views/shows/index.html.haml
.homepage
    = link_to 'ADD NEW SHOW', new_show_path, class: "btn btn-info"
    
    %h3 BOOKMARKS
    = render partial: "showTiles", locals: {shows: @bookmarks}
    
    %h3 WATCHLIST
    = render partial: "showTiles", locals: {shows: @watchlist}
    
    %h3 ARCHIVE
    = render partial: "showTiles", locals: {shows: @archive}

app/views/shows/new.html.haml
%p.warning#errors{style:"display: none;"}

.indented
    %h4#selection-categories
        Would you like to
        %button{class: "btn btn-info", "onclick": "category('bookmark')"} Bookmark a Show
        or
        %button{class: "btn btn-info", "onclick": "category('watchlist')"} Add to Watchlist
    
    #tmdb-form-div{style:"display: none;"}
        = render 'tmdbForm'
        
    
    %br
    #bookmark{style:"display: none;"}
        .indented
            #selection-shows{style:"display: none;"}
            %h4#selection-seasons-heading{style:"display: none;"}
            .indented#selection-seasons{style:"display: none;"}
            %h4#selection-episodes-heading{style:"display: none;"}
            .indented#selection-episodes{style:"display: none;"}
            %h4#episode-info-heading{style:"display: none;"}
            .indented#episode-info{style:"display: none;"}
            
    #watchlist{style:"display: none;"}
        .indented
            #selection-shows{style:"display: none;"}
            #priority{style:"display: none;"}
                %h4 How keen are you to watch this show?
                #slidecontainer
                    %input#myRange.slider{max: "5", min: "1", type: "range", value: "1", oninput: "myFunction(this.value)"}
                    // %p{id: "keen-scale"}
                    %h5
                        %strong#keen-scale Not fussed
                = button_to "Save", '/shows', params: {name: 'nothingYet', show_id: 0, category: 'Watchlist', priority: 1}, class: "btn btn-success", id: 'watchlist-save'
        
= link_to 'Cancel', shows_path, class: "btn btn-info"

app/views/shows/search_id.js.haml
$('#selection-episodes-heading').hide();
$('#selection-episodes').hide();
$('#episode-info-heading').hide();
$('#episode-info').hide();

$('#selection-seasons-heading').text('Which Season?');
$('#selection-seasons-heading').show();

$('#selection-seasons').hide();
$('#selection-seasons').html('#{escape_javascript(render :partial => "selectSeason")}');
$('#selection-seasons').slideDown(350);

app/views/shows/search_tmdb.js.haml
// Hide parts of form
$('#selection-seasons-heading').hide();
$('#selection-seasons').hide();
$('#selection-episodes-heading').hide();
$('#selection-episodes').hide();
$('#episode-info-heading').hide();
$('#episode-info').hide();
$('#priority').hide()
- if @search == 0
    $('#errors').text('FILL THE FIELD')
    $('#errors').show();
- else
    - if @search.total_results == 0
        // show doesnt exist
        // - flash[:warning] = '#{@name} could not be found in TMDb'
        $('#errors').text('#{@name} could not be found in TMDb')
        $('#errors').show();
        $('#selection-shows').hide();
    - else
        // show exists
        $('#errors').hide();
        $('#bookmark #selection-shows').html('#{escape_javascript(render :partial => "selectShow")}');
        $('#watchlist #selection-shows').html('#{escape_javascript(render :partial => "selectShow")}');
        $('#bookmark #selection-shows').slideDown(350);
        $('#watchlist #selection-shows').slideDown(350);